language: generic
services:
  # App depends on docker
  - docker

before_install:
  # Build test image
  - docker build -t knbully/complex-docker-react-test -f ./client/Dockerfile.dev ./client

script:
  # Run test script on test image
  - docker run -e CI=true knbully/complex-docker-react-test npm run test

after_success:
  # Build prod images
  - docker build -t knbully/complex-client ./client
  - docker build -t knbully/complex-nginx ./nginx
  - docker build -t knbully/complex-server ./server
  - docker build -t knbully/complex-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push knbully/complex-client
  - docker push knbully/complex-nginx
  - docker push knbully/complex-server
  - docker push knbully/complex-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-2
  app: docker-complex
  environment: DockerComplex-env
  bucket_name: elasticbeanstalk-eu-west-2-053515776978
  bucket_path: docker-complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
